before:
  hooks:
    - go mod tidy
builds:
  - id: go-brutils
    binary: brutils
    ldflags:
      - -s -w -X github.com/aureliano/go-brutils/cmd.project.version={{.Version}}
      - -X github.com/aureliano/go-brutils/cmd.project.name={{.ProjectName}}
      - -X github.com/aureliano/go-brutils/cmd.project.binName=brutils
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: aureliano
    name: go-brutils
  prerelease: auto
  mode: append